### ISSUE TITLE
Error when loading PDF

### ISSUE THREAD

**Issue by widmoser** [Birdbrain2/PdfBox-Android#14]
When I try to execute the following:

```java
PDDocument document = PDDocument.load(new File("/sdcard/Download/file.pdf"));
````

I get the following error:
```
01-14 11:56:16.064    4778-4778/? W/System.err﹕ java.io.IOException: offset < 0: -4096
01-14 11:56:16.064    4778-4778/? W/System.err﹕ at java.io.RandomAccessFile.seek(RandomAccessFile.java:597)
01-14 11:56:16.064    4778-4778/? W/System.err﹕ at org.apache.pdfbox.io.RandomAccessBufferedFileInputStream.seek(RandomAccessBufferedFileInputStream.java:102)
01-14 11:56:16.064    4778-4778/? W/System.err﹕ at org.apache.pdfbox.io.PushBackInputStream.seek(PushBackInputStream.java:218)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at org.apache.pdfbox.pdfparser.NonSequentialPDFParser.initialParse(NonSequentialPDFParser.java:476)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at org.apache.pdfbox.pdfparser.NonSequentialPDFParser.parse(NonSequentialPDFParser.java:940)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1030)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:944)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at com.mobilejazz.coltrane.example.FileDetailActivity.onCreate(FileDetailActivity.java:53)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5933)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:144)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5221)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
01-14 11:56:16.065    4778-4778/? W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-14 11:56:16.066    4778-4778/? W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Any ideas??

**Comment by widmoser** [comment]
```java
PDDocument document = PDDocument.loadLegacy(new File("/sdcard/Download/file.pdf"));
```

seems to work

**Comment by Birdbrain2** [comment]
loadLegacy will be fine until I can get this fixed

**Comment by Birdbrain2** [comment]
This should be fixed now
