### ISSUE TITLE
PDF Form with comb text field

### ISSUE THREAD

**Issue by Darksearcher** [Birdbrain2/PdfBox-Android#29]
When trying to set the value of a textfield that has comb within a form PDF the following error occurs.

```
02-27 10:09:09.299  24004-24004/com.dixieind.dixieapplication E/﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'float org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(java.lang.String)' on a null object reference
            at org.apache.pdfbox.service.interactive.form.PDAppearanceString.calculateFontSize(PDAppearanceString.java:475)
            at org.apache.pdfbox.service.interactive.form.PDAppearanceString.setAppearanceValue(PDAppearanceString.java:234)
            at org.apache.pdfbox.service.interactive.form.AppearanceGenerator.generateFieldAppearances(AppearanceGenerator.java:66)
            at org.apache.pdfbox.pdmodel.interactive.form.PDField.updateFieldAppearances(PDField.java:103)
            at org.apache.pdfbox.pdmodel.interactive.form.PDTextField.setValue(PDTextField.java:264)
            at com.dixieind.dixieapplication.PdfWriter2.viewToPdf(PdfWriter2.java:317)
            at com.dixieind.dixieapplication.GovernmentForm1.OpenAdobeReader(GovernmentForm1.java:60)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at android.view.View$1.onClick(View.java:4002)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by Birdbrain2** [comment]
What code is causing this issue? Are you filling an existing form with a comb or are you generating your own?

**Comment by Darksearcher** [comment]
Actually, I may have jumped the gun with this issue.  I'm not exactly sure how I managed to fix this issue, but it actually works fine.  I did recently update my Android Studio, maybe somehow this is related.  I will post again if the issue reoccurs. 

Sorry about that.
